spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/curation
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true;

logging.level:
  org.hibernate.SQL: debug